<?hh // strict

enum ParseTreeKind : int
{
  SCRIPT = 0;
  QUALIFIED_NAME = 1;
  REQUIRE_MULTIPLE_DIRECTIVE = 2;
  REQUIRE_ONCE_DIRECTIVE = 3;
  LITERAL = 4;
  ENUM_DECLARATION = 5;
  ENUMERATOR = 6;
  FUNCTION_DEFINITION = 7;
  PARAMETER_LIST = 8;
  PARAMETER_DECLARATION = 9;
  COMPOUND_STATEMENT = 10;
  PREDEFINED_NAME_TYPE = 11;
  KEYWORD_TYPE = 12;
  NULLABLE_TYPE = 13;
  NAMED_TYPE = 14;
  CLOSURE_TYPE = 15;
  TUPLE_TYPE = 16;
  TYPE_ARGUMENTS = 17;
  NAMESPACE_USE_DECLARATION = 18;
  NAMESPACE_USE_CLAUSE = 19;
  NAMESPACE_DEFINITION = 20;
  GENERIC_TYPE_PARAMETER = 21;
  CLASS_DECLARATION = 22;
  TRAIT_USE_CLAUSE = 23;
  CONST_DECLARATION = 24;
  CONST_DECLARATOR = 25;
  PROPERTY_DECLARATOR = 26;
  METHOD_DEFINITION = 27;
  DESTRUCTOR_DECLARATION = 28;
  CONSTRUCTOR_DECLARATION = 29;
  CONSTRUCTOR_PARAMETER = 30;
  INTERFACE_DECLARATION = 31;
  REQUIRES_EXTENDS_CLAUSE = 32;
  REQUIRES_IMPLEMENTS_CLAUSE = 33;
  TRAIT_DECLARATION = 34;
  PARSE_ERROR = 35;
}
