<?hh //strict

enum ParseTreeKind : int
{
  SCRIPT = 0;

  // Declarations
  REQUIRE_MULTIPLE_DIRECTIVE = 1;
  REQUIRE_ONCE_DIRECTIVE = 2;

  FUNCTION_DEFINITION = 3;
  PARAMETER_LIST = 4;
  PARAMETER_DECLARATION = 5;

  // Expressions
  LITERAL = 100;

  // Statements
  COMPOUND_STATEMENT = 200;

  // Types
  KEYWORD_TYPE = 300;
  PREDEFINED_NAME_TYPE = 301;
  NULLABLE_TYPE = 302;
  ARRAY_TYPE = 303;
  TYPE_ARGUMENTS_TYPE = 304;
}
